# Generated by Django 4.1.7 on 2023-03-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
    ]
